from setuptools import setup, find_packages


setup(
    name="medical_research_backend",
    version="0.1.0",
    packages=find_packages(),
    description="Backend services for the medical research project",
    author="Your Name",
    author_email="your.email@example.com",
    install_requires=[
'annotated-types',
'anyio',
'certifi',
'click',
'dnspython',
'email_validator',
'fastapi',
'fastapi',
'h11',
'httpcore',
'httptools',
'httpx',
'idna',
'Jinja2',
'markdown',
'MarkupSafe',
'mdurl',
'pydantic',
'pydantic',
'pydantic_core',
'Pygments',
'PyYAML',
'rich',
'rich',
'sentry-sdk',
'shellingham',
'sniffio',
'starlette',
'typer',
'typing_extensions',
'urllib3',
'uvicorn',
'uvloop',
'watchfiles',
'websockets'
    ],
)
